//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBrasil.OpenBanking.BackOfficeTed.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiInfos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiInfos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABCBrasil.OpenBanking.BackOfficeTed.Api.Resources.ApiInfos", typeof(ApiInfos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Banking - API de BackOfficeTed OpenBanking.
        /// </summary>
        internal static string ApiDescription {
            get {
                return ResourceManager.GetString("ApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCBrasil.OpenBanking.BackOfficeTed.Api.
        /// </summary>
        internal static string ApiName {
            get {
                return ResourceManager.GetString("ApiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta versão da API está descontinuada..
        /// </summary>
        internal static string ApiVersionDeprecated {
            get {
                return ResourceManager.GetString("ApiVersionDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contato@abcbrasil.com.br.
        /// </summary>
        internal static string BankEmail {
            get {
                return ResourceManager.GetString("BankEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC Brasil.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.abcbrasil.com.br/.
        /// </summary>
        internal static string BankUrl {
            get {
                return ResourceManager.GetString("BankUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.abcbrasil.com.br/license.
        /// </summary>
        internal static string BankUrlTerms {
            get {
                return ResourceManager.GetString("BankUrlTerms", resourceCulture);
            }
        }
    }
}
