//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBrasil.OpenBanking.BackOfficeTed.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FriendlyMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FriendlyMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABCBrasil.OpenBanking.BackOfficeTed.Core.Resources.FriendlyMessages", typeof(FriendlyMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID do cliente inválido..
        /// </summary>
        public static string ControlerErrorClientIDInvalid {
            get {
                return ResourceManager.GetString("ControlerErrorClientIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código do cliente inválido.
        /// </summary>
        public static string ErrorValidaCodigoClienteUsuario {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoClienteUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de barras ou linha digitável inválido..
        /// </summary>
        public static string ErrorValidaCodigoPagamento {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de barras ou linha digitável deve ser informado..
        /// </summary>
        public static string ErrorValidaCodigoPagamentoEmpty {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoPagamentoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Código de Pagamento deve ter no máximo 47 caracteres.
        /// </summary>
        public static string ErrorValidaCodigoPagamentoMax47 {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoPagamentoMax47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Código de Pagamento deve ter no mínimo 44 caracteres.
        /// </summary>
        public static string ErrorValidaCodigoPagamentoMin44 {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoPagamentoMin44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email inválido.
        /// </summary>
        public static string ErrorValidEmailInvalid {
            get {
                return ResourceManager.GetString("ErrorValidEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id não informado.
        /// </summary>
        public static string ErrorValidIdEmpty {
            get {
                return ResourceManager.GetString("ErrorValidIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id informado é inválido.
        /// </summary>
        public static string ErrorValidIdInvalid {
            get {
                return ResourceManager.GetString("ErrorValidIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome deve ter no mínimo 10 caracteres.
        /// </summary>
        public static string ErrorValidName10 {
            get {
                return ResourceManager.GetString("ErrorValidName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome não informado.
        /// </summary>
        public static string ErrorValidNameEmpty {
            get {
                return ResourceManager.GetString("ErrorValidNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O parâmetro {0} não é válido..
        /// </summary>
        public static string ErrorValidParameter {
            get {
                return ResourceManager.GetString("ErrorValidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha deve ter no mínimo 5 caracteres.
        /// </summary>
        public static string ErrorValidPassword5 {
            get {
                return ResourceManager.GetString("ErrorValidPassword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha não informada.
        /// </summary>
        public static string ErrorValidPasswordEmpty {
            get {
                return ResourceManager.GetString("ErrorValidPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código Tricon não é permitido na consulta.
        /// </summary>
        public static string ErrorValidTricon {
            get {
                return ResourceManager.GetString("ErrorValidTricon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao abrir lote de Pagamento para o centro de processamento.
        /// </summary>
        public static string ErroServicoAbrirCorePagamento {
            get {
                return ResourceManager.GetString("ErroServicoAbrirCorePagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao aplicar as validações do titulo.
        /// </summary>
        public static string ErroServicoAplicaValidacoesTitulo {
            get {
                return ResourceManager.GetString("ErroServicoAplicaValidacoesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao calcular pagamento.
        /// </summary>
        public static string ErroServicoCalcularPagamento {
            get {
                return ResourceManager.GetString("ErroServicoCalcularPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao consultar Situação do Pagamento.
        /// </summary>
        public static string ErroServicoConsultarPagamento {
            get {
                return ResourceManager.GetString("ErroServicoConsultarPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta informada não pertence ao cliente.
        /// </summary>
        public static string ErroServicoContaCliente {
            get {
                return ResourceManager.GetString("ErroServicoContaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao obter data de exceção.
        /// </summary>
        public static string ErroServicoDataExcecao {
            get {
                return ResourceManager.GetString("ErroServicoDataExcecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao validar dia útil.
        /// </summary>
        public static string ErroServicoDiaUtil {
            get {
                return ResourceManager.GetString("ErroServicoDiaUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao enviar o Pagamento para o centro de processamento.
        /// </summary>
        public static string ErroServicoEnviarParaCorePagamento {
            get {
                return ResourceManager.GetString("ErroServicoEnviarParaCorePagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao extrair dados do título.
        /// </summary>
        public static string ErroServicoExtrairDadosCip {
            get {
                return ResourceManager.GetString("ErroServicoExtrairDadosCip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao fechar lote de Pagamento para o centro de processamento.
        /// </summary>
        public static string ErroServicoFecharCorePagamento {
            get {
                return ResourceManager.GetString("ErroServicoFecharCorePagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao obter horários da transação.
        /// </summary>
        public static string ErroServicoHorarioTransacao {
            get {
                return ResourceManager.GetString("ErroServicoHorarioTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título inapto para pagamento ou não consistido..
        /// </summary>
        public static string ErroServicoInaptoNConsistido {
            get {
                return ResourceManager.GetString("ErroServicoInaptoNConsistido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao registrar o Pagamento.
        /// </summary>
        public static string ErroServicoIncluirPagamento {
            get {
                return ResourceManager.GetString("ErroServicoIncluirPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao Incluir Registro de Evento.
        /// </summary>
        public static string ErroServicoIncluirRegistroEvento {
            get {
                return ResourceManager.GetString("ErroServicoIncluirRegistroEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento não encontrado..
        /// </summary>
        public static string ErroServicoPagamentoNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroServicoPagamentoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excedeu o tempo limite da operação, tente novamente mais tarde..
        /// </summary>
        public static string ErroServicoTempoLimite {
            get {
                return ResourceManager.GetString("ErroServicoTempoLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título já registrado na base.
        /// </summary>
        public static string ErroServicoTituloJaRegistrado {
            get {
                return ResourceManager.GetString("ErroServicoTituloJaRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título não permite valor divergente..
        /// </summary>
        public static string ErroServicoTituloValorDivergente {
            get {
                return ResourceManager.GetString("ErroServicoTituloValorDivergente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao checar TpAutcRecbtVlrDivgte..
        /// </summary>
        public static string ErroServicoTpAutcRecbtVlrDivgte {
            get {
                return ResourceManager.GetString("ErroServicoTpAutcRecbtVlrDivgte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agencia não informada.
        /// </summary>
        public static string ErroValidaAgencia {
            get {
                return ResourceManager.GetString("ErroValidaAgencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código do cliente não informado.
        /// </summary>
        public static string ErroValidaCodigoCliente {
            get {
                return ResourceManager.GetString("ErroValidaCodigoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código do pagamento não informado.
        /// </summary>
        public static string ErroValidaCodigoPagamento {
            get {
                return ResourceManager.GetString("ErroValidaCodigoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta não informada.
        /// </summary>
        public static string ErroValidaConta {
            get {
                return ResourceManager.GetString("ErroValidaConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data pagamento não informada.
        /// </summary>
        public static string ErroValidaDataPagamento {
            get {
                return ResourceManager.GetString("ErroValidaDataPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de pagamento deve ser igual ou superior a data do dia.
        /// </summary>
        public static string ErroValidaDataPagamentoInferior {
            get {
                return ResourceManager.GetString("ErroValidaDataPagamentoInferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador de Pagamento não informado..
        /// </summary>
        public static string ErroValidaIdentificadorPagamento {
            get {
                return ResourceManager.GetString("ErroValidaIdentificadorPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificação do pagamento não informado.
        /// </summary>
        public static string ErroValidaIdPagamento {
            get {
                return ResourceManager.GetString("ErroValidaIdPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Protocolo não informado..
        /// </summary>
        public static string ErroValidaProtocolo {
            get {
                return ResourceManager.GetString("ErroValidaProtocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Protoloco inválido.
        /// </summary>
        public static string ErroValidaProtocoloInvalido {
            get {
                return ResourceManager.GetString("ErroValidaProtocoloInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Url de notificação não informada.
        /// </summary>
        public static string ErroValidaUrlNotificacao {
            get {
                return ResourceManager.GetString("ErroValidaUrlNotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor do pagamento não informado.
        /// </summary>
        public static string ErroValidaValorPagamento {
            get {
                return ResourceManager.GetString("ErroValidaValorPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é permitido valor de tributo ou concessionária divergente do código de barras.
        /// </summary>
        public static string ErroValidaValorTriCon {
            get {
                return ResourceManager.GetString("ErroValidaValorTriCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informar um valor para pagamento maior que 0.
        /// </summary>
        public static string ErroValidaValorZeroPagamento {
            get {
                return ResourceManager.GetString("ErroValidaValorZeroPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma falha na sua solicitação. Por favor tente novamente..
        /// </summary>
        public static string GeneralFail {
            get {
                return ResourceManager.GetString("GeneralFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fora do horário permitido para o pagamento, horário inicio: {0} e horário fim {1}.
        /// </summary>
        public static string InfoServicoForaHorario {
            get {
                return ResourceManager.GetString("InfoServicoForaHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao obter próximo dia útil.
        /// </summary>
        public static string InfoServicoProximoDiaUtil {
            get {
                return ResourceManager.GetString("InfoServicoProximoDiaUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título excedeu a data limite para pagamento.
        /// </summary>
        public static string InfoServicoTituloExcedeDataLimite {
            get {
                return ResourceManager.GetString("InfoServicoTituloExcedeDataLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título execedeu o limite de pagamentos parciais.
        /// </summary>
        public static string InfoServicoTituloExcedeQtdPagtos {
            get {
                return ResourceManager.GetString("InfoServicoTituloExcedeQtdPagtos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título inapto para pagamento.
        /// </summary>
        public static string InfoServicoTituloInapto {
            get {
                return ResourceManager.GetString("InfoServicoTituloInapto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf inválido.
        /// </summary>
        public static string InvalidCpf {
            get {
                return ResourceManager.GetString("InvalidCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Favor informar o parâmetro {0}..
        /// </summary>
        public static string RequestParameter {
            get {
                return ResourceManager.GetString("RequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boleto não localizado na CIP..
        /// </summary>
        public static string ServiceErrorBoletoNotFound {
            get {
                return ResourceManager.GetString("ServiceErrorBoletoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao atualizar situação pagamento..
        /// </summary>
        public static string ServiceErrorCallbackCoreAtualizarSituacao {
            get {
                return ResourceManager.GetString("ServiceErrorCallbackCoreAtualizarSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente não localizado.
        /// </summary>
        public static string ServiceErrorClientNotFound {
            get {
                return ResourceManager.GetString("ServiceErrorClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao excluir Cliente [ID].
        /// </summary>
        public static string ServiceErrorDeleteClients {
            get {
                return ResourceManager.GetString("ServiceErrorDeleteClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma falha na consulta na Api {0}.
        /// </summary>
        public static string ServiceErrorExternalApi {
            get {
                return ResourceManager.GetString("ServiceErrorExternalApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao localizar dados do Cliente [ID].
        /// </summary>
        public static string ServiceErrorFindClient {
            get {
                return ResourceManager.GetString("ServiceErrorFindClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao localizar Clientes.
        /// </summary>
        public static string ServiceErrorFindClients {
            get {
                return ResourceManager.GetString("ServiceErrorFindClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao obter boleto..
        /// </summary>
        public static string ServiceErrorObterBoleto {
            get {
                return ResourceManager.GetString("ServiceErrorObterBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao localizar Boleto..
        /// </summary>
        public static string ServiceErrorObterSituacaoBoleto {
            get {
                return ResourceManager.GetString("ServiceErrorObterSituacaoBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao gravar os dados do Cliente.
        /// </summary>
        public static string ServiceErrorPostClient {
            get {
                return ResourceManager.GetString("ServiceErrorPostClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao processar arquivo ted..
        /// </summary>
        public static string ServiceErrorProcessaarquivo {
            get {
                return ResourceManager.GetString("ServiceErrorProcessaarquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título já registrado na base.
        /// </summary>
        public static string ServiceErrorTituloJaRegistrado {
            get {
                return ResourceManager.GetString("ServiceErrorTituloJaRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao atualizar Cliente.
        /// </summary>
        public static string ServiceErrorUpdateClients {
            get {
                return ResourceManager.GetString("ServiceErrorUpdateClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de identificação do pagamento &apos;{0}&apos; já utilizado em outro protocolo, favor iniciar um novo processo de pagamento..
        /// </summary>
        public static string ServicoInfoIdPagtoExiste {
            get {
                return ResourceManager.GetString("ServicoInfoIdPagtoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento enviado para processamento..
        /// </summary>
        public static string ServicoInfoPagamentoSucesso {
            get {
                return ResourceManager.GetString("ServicoInfoPagamentoSucesso", resourceCulture);
            }
        }
    }
}
