//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBrasil.OpenBanking.BackOfficeTed.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FriendlyMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FriendlyMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABCBrasil.OpenBanking.BackOfficeTed.Core.Resources.FriendlyMessages", typeof(FriendlyMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID do cliente inválido..
        /// </summary>
        public static string ControlerErrorClientIDInvalid {
            get {
                return ResourceManager.GetString("ControlerErrorClientIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do cliente inválido.
        /// </summary>
        public static string ErrorValidaCodigoClienteUsuario {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoClienteUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de barras ou linha digitável inválido..
        /// </summary>
        public static string ErrorValidaCodigoPagamento {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de barras ou linha digitável deve ser informado..
        /// </summary>
        public static string ErrorValidaCodigoPagamentoEmpty {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoPagamentoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código de Pagamento deve ter no máximo 47 caracteres.
        /// </summary>
        public static string ErrorValidaCodigoPagamentoMax47 {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoPagamentoMax47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código de Pagamento deve ter no mínimo 44 caracteres.
        /// </summary>
        public static string ErrorValidaCodigoPagamentoMin44 {
            get {
                return ResourceManager.GetString("ErrorValidaCodigoPagamentoMin44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string ErrorValidEmailInvalid {
            get {
                return ResourceManager.GetString("ErrorValidEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id não informado.
        /// </summary>
        public static string ErrorValidIdEmpty {
            get {
                return ResourceManager.GetString("ErrorValidIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id informado é inválido.
        /// </summary>
        public static string ErrorValidIdInvalid {
            get {
                return ResourceManager.GetString("ErrorValidIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ter no mínimo 10 caracteres.
        /// </summary>
        public static string ErrorValidName10 {
            get {
                return ResourceManager.GetString("ErrorValidName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome não informado.
        /// </summary>
        public static string ErrorValidNameEmpty {
            get {
                return ResourceManager.GetString("ErrorValidNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro {0} não é válido..
        /// </summary>
        public static string ErrorValidParameter {
            get {
                return ResourceManager.GetString("ErrorValidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve ter no mínimo 5 caracteres.
        /// </summary>
        public static string ErrorValidPassword5 {
            get {
                return ResourceManager.GetString("ErrorValidPassword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não informada.
        /// </summary>
        public static string ErrorValidPasswordEmpty {
            get {
                return ResourceManager.GetString("ErrorValidPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Tricon não é permitido na consulta.
        /// </summary>
        public static string ErrorValidTricon {
            get {
                return ResourceManager.GetString("ErrorValidTricon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao abrir lote de Pagamento para o centro de processamento.
        /// </summary>
        public static string ErroServicoAbrirCorePagamento {
            get {
                return ResourceManager.GetString("ErroServicoAbrirCorePagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao aplicar as validações do titulo.
        /// </summary>
        public static string ErroServicoAplicaValidacoesTitulo {
            get {
                return ResourceManager.GetString("ErroServicoAplicaValidacoesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao calcular pagamento.
        /// </summary>
        public static string ErroServicoCalcularPagamento {
            get {
                return ResourceManager.GetString("ErroServicoCalcularPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao consultar Situação do Pagamento.
        /// </summary>
        public static string ErroServicoConsultarPagamento {
            get {
                return ResourceManager.GetString("ErroServicoConsultarPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta informada não pertence ao cliente.
        /// </summary>
        public static string ErroServicoContaCliente {
            get {
                return ResourceManager.GetString("ErroServicoContaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao obter data de exceção.
        /// </summary>
        public static string ErroServicoDataExcecao {
            get {
                return ResourceManager.GetString("ErroServicoDataExcecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao validar dia útil.
        /// </summary>
        public static string ErroServicoDiaUtil {
            get {
                return ResourceManager.GetString("ErroServicoDiaUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao enviar o Pagamento para o centro de processamento.
        /// </summary>
        public static string ErroServicoEnviarParaCorePagamento {
            get {
                return ResourceManager.GetString("ErroServicoEnviarParaCorePagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao extrair dados do título.
        /// </summary>
        public static string ErroServicoExtrairDadosCip {
            get {
                return ResourceManager.GetString("ErroServicoExtrairDadosCip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao fechar lote de Pagamento para o centro de processamento.
        /// </summary>
        public static string ErroServicoFecharCorePagamento {
            get {
                return ResourceManager.GetString("ErroServicoFecharCorePagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao obter horários da transação.
        /// </summary>
        public static string ErroServicoHorarioTransacao {
            get {
                return ResourceManager.GetString("ErroServicoHorarioTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título inapto para pagamento ou não consistido..
        /// </summary>
        public static string ErroServicoInaptoNConsistido {
            get {
                return ResourceManager.GetString("ErroServicoInaptoNConsistido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao registrar o Pagamento.
        /// </summary>
        public static string ErroServicoIncluirPagamento {
            get {
                return ResourceManager.GetString("ErroServicoIncluirPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao Incluir Registro de Evento.
        /// </summary>
        public static string ErroServicoIncluirRegistroEvento {
            get {
                return ResourceManager.GetString("ErroServicoIncluirRegistroEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento não encontrado..
        /// </summary>
        public static string ErroServicoPagamentoNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroServicoPagamentoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excedeu o tempo limite da operação, tente novamente mais tarde..
        /// </summary>
        public static string ErroServicoTempoLimite {
            get {
                return ResourceManager.GetString("ErroServicoTempoLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título já registrado na base.
        /// </summary>
        public static string ErroServicoTituloJaRegistrado {
            get {
                return ResourceManager.GetString("ErroServicoTituloJaRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título não permite valor divergente..
        /// </summary>
        public static string ErroServicoTituloValorDivergente {
            get {
                return ResourceManager.GetString("ErroServicoTituloValorDivergente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao checar TpAutcRecbtVlrDivgte..
        /// </summary>
        public static string ErroServicoTpAutcRecbtVlrDivgte {
            get {
                return ResourceManager.GetString("ErroServicoTpAutcRecbtVlrDivgte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencia não informada.
        /// </summary>
        public static string ErroValidaAgencia {
            get {
                return ResourceManager.GetString("ErroValidaAgencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do cliente não informado.
        /// </summary>
        public static string ErroValidaCodigoCliente {
            get {
                return ResourceManager.GetString("ErroValidaCodigoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do pagamento não informado.
        /// </summary>
        public static string ErroValidaCodigoPagamento {
            get {
                return ResourceManager.GetString("ErroValidaCodigoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta não informada.
        /// </summary>
        public static string ErroValidaConta {
            get {
                return ResourceManager.GetString("ErroValidaConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data pagamento não informada.
        /// </summary>
        public static string ErroValidaDataPagamento {
            get {
                return ResourceManager.GetString("ErroValidaDataPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de pagamento deve ser igual ou superior a data do dia.
        /// </summary>
        public static string ErroValidaDataPagamentoInferior {
            get {
                return ResourceManager.GetString("ErroValidaDataPagamentoInferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador de Pagamento não informado..
        /// </summary>
        public static string ErroValidaIdentificadorPagamento {
            get {
                return ResourceManager.GetString("ErroValidaIdentificadorPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação do pagamento não informado.
        /// </summary>
        public static string ErroValidaIdPagamento {
            get {
                return ResourceManager.GetString("ErroValidaIdPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocolo não informado..
        /// </summary>
        public static string ErroValidaProtocolo {
            get {
                return ResourceManager.GetString("ErroValidaProtocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protoloco inválido.
        /// </summary>
        public static string ErroValidaProtocoloInvalido {
            get {
                return ResourceManager.GetString("ErroValidaProtocoloInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url de notificação não informada.
        /// </summary>
        public static string ErroValidaUrlNotificacao {
            get {
                return ResourceManager.GetString("ErroValidaUrlNotificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do pagamento não informado.
        /// </summary>
        public static string ErroValidaValorPagamento {
            get {
                return ResourceManager.GetString("ErroValidaValorPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido valor de tributo ou concessionária divergente do código de barras.
        /// </summary>
        public static string ErroValidaValorTriCon {
            get {
                return ResourceManager.GetString("ErroValidaValorTriCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informar um valor para pagamento maior que 0.
        /// </summary>
        public static string ErroValidaValorZeroPagamento {
            get {
                return ResourceManager.GetString("ErroValidaValorZeroPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha na sua solicitação. Por favor tente novamente..
        /// </summary>
        public static string GeneralFail {
            get {
                return ResourceManager.GetString("GeneralFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fora do horário permitido para o pagamento, horário inicio: {0} e horário fim {1}.
        /// </summary>
        public static string InfoServicoForaHorario {
            get {
                return ResourceManager.GetString("InfoServicoForaHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao obter próximo dia útil.
        /// </summary>
        public static string InfoServicoProximoDiaUtil {
            get {
                return ResourceManager.GetString("InfoServicoProximoDiaUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título excedeu a data limite para pagamento.
        /// </summary>
        public static string InfoServicoTituloExcedeDataLimite {
            get {
                return ResourceManager.GetString("InfoServicoTituloExcedeDataLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título execedeu o limite de pagamentos parciais.
        /// </summary>
        public static string InfoServicoTituloExcedeQtdPagtos {
            get {
                return ResourceManager.GetString("InfoServicoTituloExcedeQtdPagtos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título inapto para pagamento.
        /// </summary>
        public static string InfoServicoTituloInapto {
            get {
                return ResourceManager.GetString("InfoServicoTituloInapto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf inválido.
        /// </summary>
        public static string InvalidCpf {
            get {
                return ResourceManager.GetString("InvalidCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor informar o parâmetro {0}..
        /// </summary>
        public static string RequestParameter {
            get {
                return ResourceManager.GetString("RequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boleto não localizado na CIP..
        /// </summary>
        public static string ServiceErrorBoletoNotFound {
            get {
                return ResourceManager.GetString("ServiceErrorBoletoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao atualizar situação pagamento..
        /// </summary>
        public static string ServiceErrorCallbackCoreAtualizarSituacao {
            get {
                return ResourceManager.GetString("ServiceErrorCallbackCoreAtualizarSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não localizado.
        /// </summary>
        public static string ServiceErrorClientNotFound {
            get {
                return ResourceManager.GetString("ServiceErrorClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao excluir Cliente [ID].
        /// </summary>
        public static string ServiceErrorDeleteClients {
            get {
                return ResourceManager.GetString("ServiceErrorDeleteClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha na consulta na Api {0}.
        /// </summary>
        public static string ServiceErrorExternalApi {
            get {
                return ResourceManager.GetString("ServiceErrorExternalApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao localizar dados do Cliente [ID].
        /// </summary>
        public static string ServiceErrorFindClient {
            get {
                return ResourceManager.GetString("ServiceErrorFindClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao localizar Clientes.
        /// </summary>
        public static string ServiceErrorFindClients {
            get {
                return ResourceManager.GetString("ServiceErrorFindClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao obter boleto..
        /// </summary>
        public static string ServiceErrorObterBoleto {
            get {
                return ResourceManager.GetString("ServiceErrorObterBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao localizar Boleto..
        /// </summary>
        public static string ServiceErrorObterSituacaoBoleto {
            get {
                return ResourceManager.GetString("ServiceErrorObterSituacaoBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao gravar os dados do Cliente.
        /// </summary>
        public static string ServiceErrorPostClient {
            get {
                return ResourceManager.GetString("ServiceErrorPostClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título já registrado na base.
        /// </summary>
        public static string ServiceErrorTituloJaRegistrado {
            get {
                return ResourceManager.GetString("ServiceErrorTituloJaRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao atualizar Cliente.
        /// </summary>
        public static string ServiceErrorUpdateClients {
            get {
                return ResourceManager.GetString("ServiceErrorUpdateClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de identificação do pagamento &apos;{0}&apos; já utilizado em outro protocolo, favor iniciar um novo processo de pagamento..
        /// </summary>
        public static string ServicoInfoIdPagtoExiste {
            get {
                return ResourceManager.GetString("ServicoInfoIdPagtoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento enviado para processamento..
        /// </summary>
        public static string ServicoInfoPagamentoSucesso {
            get {
                return ResourceManager.GetString("ServicoInfoPagamentoSucesso", resourceCulture);
            }
        }
    }
}
